name: intake-ga-dev
dependencies:
  - google-api-python-client
  # google-auth-httplib2
  - google-auth-oauthlib
  # oauth2client
  - pandas
  - intake
  - flake8
channels:
  - defaults
  - conda-forge